name: flutterpad
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

isar_version: &isar_version 3.1.0

dependencies:
  clock: ^1.1.1
  connectivity_plus: ^5.0.2
  device_preview: ^1.1.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: *isar_version

flutter:
  uses-material-design: true
